{"name": "Негативная проверка создания юзера, который уже существует", "status": "passed", "description": "Запрос должен вернуть ошибку и правильный код ответа", "attachments": [{"name": "stdout", "source": "cc3ce62a-604a-4567-abea-81e918fbecf5-attachment.txt", "type": "text/plain"}], "start": 1723366563806, "stop": 1723366564328, "uuid": "1255b6a0-8808-4607-9c28-2e94aea28d84", "historyId": "a1519a2bb1e317d870373acf01e4ca49", "testCaseId": "a1519a2bb1e317d870373acf01e4ca49", "fullName": "tests.test_create_user.test_creating_2_identical_users.TestCreateUser#test_сreate_2_identical_couriers_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('reg')"}, {"name": "parentSuite", "value": "tests.test_create_user"}, {"name": "suite", "value": "test_creating_2_identical_users"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-IKUPUFD"}, {"name": "thread", "value": "16804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user.test_creating_2_identical_users"}]}